[package]
name = "str-gradient"
version = "0.1.0"
authors = ["Eievui <14899090+GreenAndEievui@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
